2025-03-03 23:10:20 - [INIT] with clock rate 4 and peers ['localhost:50050', 'localhost:50052'], [0, 2]
2025-03-03 23:10:22 - [INTERNAL], Logical clock: 1
2025-03-03 23:10:22 - [INTERNAL], Logical clock: 2
2025-03-03 23:10:22 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:22.904776-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:23 - [INTERNAL], Logical clock: 4
2025-03-03 23:10:23 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:23.413603-05:00"}"
>
2025-03-03 23:10:23 - [INTERNAL], Logical clock: 6
2025-03-03 23:10:23 - [INTERNAL], Logical clock: 7
2025-03-03 23:10:24 - [INTERNAL], Logical clock: 8
2025-03-03 23:10:24 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:24.430629-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:24 - [INTERNAL], Logical clock: 10
2025-03-03 23:10:24 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:24.939671-05:00"}"
>
2025-03-03 23:10:24 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:24.940684-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:25 - [INTERNAL], Logical clock: 12
2025-03-03 23:10:25 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:25.449527-05:00"}"
>
2025-03-03 23:10:25 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:25.704905-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:25 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:25.95964-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:26 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:26.215779-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:26 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:26.465924-05:00"}"
>
2025-03-03 23:10:26 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:26.467038-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:26 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:26.716154-05:00"}"
>
2025-03-03 23:10:26 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:26.96805-05:00"}"
>
2025-03-03 23:10:27 - [INTERNAL], Logical clock: 20
2025-03-03 23:10:27 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:27.47628-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:27 - [INTERNAL], Logical clock: 22
2025-03-03 23:10:27 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:27.984495-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:27 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:27.985557-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:28 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:28.235583-05:00"}"
>
2025-03-03 23:10:28 - [INTERNAL], Logical clock: 25
2025-03-03 23:10:28 - [INTERNAL], Logical clock: 26
2025-03-03 23:10:28 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:28.996008-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:29 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:29.251058-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:29 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:29.506067-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:29 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:29.760872-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:29 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:29.761709-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:30 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:30.016742-05:00"}"
>
2025-03-03 23:10:30 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:30.270768-05:00"}"
>
2025-03-03 23:10:30 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:30.525714-05:00"}"
>
2025-03-03 23:10:30 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:30.781734-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:31 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:31.035952-05:00"}"
>
2025-03-03 23:10:31 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:31.286366-05:00"}"
>
2025-03-03 23:10:31 - [INTERNAL], Logical clock: 37
2025-03-03 23:10:31 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:31.797132-05:00"}"
>
2025-03-03 23:10:32 - [INTERNAL], Logical clock: 39
2025-03-03 23:10:32 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:32.306709-05:00"}"
>
