2025-03-03 23:10:20 - [INIT] with clock rate 5 and peers ['localhost:50050', 'localhost:50051'], [0, 1]
2025-03-03 23:10:22 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:22.395225-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:22 - [INTERNAL], Logical clock: 2
2025-03-03 23:10:22 - [INTERNAL], Logical clock: 3
2025-03-03 23:10:23 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:23.009289-05:00"}"
>
2025-03-03 23:10:23 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:23.212298-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:23 - [INTERNAL], Logical clock: 6
2025-03-03 23:10:23 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:23.61867-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:23 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:23.822709-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:24 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:24.026215-05:00"}"
>
2025-03-03 23:10:24 - [INTERNAL], Logical clock: 10
2025-03-03 23:10:24 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:24.430511-05:00"}"
>
2025-03-03 23:10:24 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:24.633247-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:24 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:24.634457-05:00"}"
>
2025-03-03 23:10:24 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:24.834136-05:00"}"
>
2025-03-03 23:10:25 - [INTERNAL], Logical clock: 14
2025-03-03 23:10:25 - [INTERNAL], Logical clock: 15
2025-03-03 23:10:25 - [INTERNAL], Logical clock: 16
2025-03-03 23:10:25 - [INTERNAL], Logical clock: 17
2025-03-03 23:10:25 - [INTERNAL], Logical clock: 18
2025-03-03 23:10:26 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:26.06094-05:00"}"
>
2025-03-03 23:10:26 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:26.262757-05:00"}"
>
2025-03-03 23:10:26 - [INTERNAL], Logical clock: 21
2025-03-03 23:10:26 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:26.67175-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:26 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:26.873568-05:00"}"
>
2025-03-03 23:10:27 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:27.078686-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:27 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:27.279566-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:27 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:27.280891-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:27 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:27.483297-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:27 - [INTERNAL], Logical clock: 27
2025-03-03 23:10:27 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:27.89113-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:27 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:27.892076-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:28 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:28.09669-05:00"}"
>
2025-03-03 23:10:28 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:28.302036-05:00"}"
>
2025-03-03 23:10:28 - [INTERNAL], Logical clock: 31
2025-03-03 23:10:28 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:28.70981-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:28 - [INTERNAL], Logical clock: 33
2025-03-03 23:10:29 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:29.116772-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:29 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:29.321394-05:00"}"
>
2025-03-03 23:10:29 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:29.526572-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:29 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:29.730281-05:00"}"
>
2025-03-03 23:10:29 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:29.731383-05:00"}"
>
2025-03-03 23:10:29 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:29.934593-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:30 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:30.137621-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:30 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:30.339746-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:30 - [INTERNAL], Logical clock: 41
2025-03-03 23:10:30 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:30.748687-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:30 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:30.952753-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:31 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:31.157574-05:00"}"
>
2025-03-03 23:10:31 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:31.158209-05:00"}"
>
2025-03-03 23:10:31 - [INTERNAL], Logical clock: 45
2025-03-03 23:10:31 - [INTERNAL], Logical clock: 46
2025-03-03 23:10:31 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:31.767924-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:31 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:31.969284-05:00"}"
>
2025-03-03 23:10:32 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:32.171944-05:00"}"
>
2025-03-03 23:10:32 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-03T23:10:32.377325-05:00", grpc_status:2, grpc_message:"Exception calling application: \'Logger\' object is not callable"}"
>
2025-03-03 23:10:32 - <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'Logger' object is not callable"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: \'Logger\' object is not callable", grpc_status:2, created_time:"2025-03-03T23:10:32.378314-05:00"}"
>
